name: Test and deploy

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env file
        run: cp .env.ci .env

      - name: Create database file
        run: touch database/database.sqlite

      - name: Generate the application key
        run: php artisan key:generate

      - name: Create a cache file
        run: php artisan config:cache

      - name: Create a route cache file
        run: php artisan route:cache

      - name: Migrate database
        run: php artisan migrate

      - name: Install Laravel Passport
        run: php artisan passport:install

      - name: Run test suite
        run: composer run-script test

      - name: Extract branch name
        run: |
          echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"

      - name: Deploy to Dokku
        if: env.BRANCH_NAME == 'master'
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@ssh.milanvit.net:22/kaji'
          ssh_host_key: ${{ secrets.SSH_HOST_KEY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
